export const GET_DESTINATIONS_REQUEST = 'GET_DESTINATIONS_REQUEST'
export const GET_DESTINATIONS_SUCCESS = 'GET_DESTINATIONS_SUCCESS'
export const GET_DESTINATIONS_FAIL= 'GET_DESTINATIONS_FAIL'

export const GET_DESTINATION_DETAILS_REQUEST = 'GET_DESTINATION_DETAILS_REQUEST'
export const GET_DESTINATION_DETAILS_SUCCESS = 'GET_DESTINATION_DETAILS_SUCCESS'
export const GET_DESTINATION_DETAILS_FAIL= 'GET_DESTINATION_DETAILS_FAIL'

