export const TRIP_LIST_REQUEST = 'TRIP_LIST_REQUEST'
export const TRIP_LIST_SUCCESS = 'TRIP_LIST_SUCCESS'
export const TRIP_LIST_FAIL = 'TRIP_LIST_FAIL'


export const TRIP_DETAILS_REQUEST = 'TRIP_DETAILS_REQUEST'
export const TRIP_DETAILS_SUCCESS = 'TRIP_DETAILS_SUCCESS'
export const TRIP_DETAILS_FAIL = 'TRIP_DETAILS_FAIL'

export const SAVE_BOOKING_INFO = 'SAVE_BOOKING_INFO'

export const CONFIRM_BOOKING_REQUEST = 'CONFIRM_BOOKING_REQUEST'
export const CONFIRM_BOOKING_SUCCESS = 'CONFIRM_BOOKING_SUCCESS'
export const CONFIRM_BOOKING_FAIL = 'CONFIRM_BOOKING_FAIL'

export const GET_BOOKED_TRIP_REQUEST = 'GET_BOOKED_TRIP_REQUEST'
export const GET_BOOKED_TRIP_SUCCESS = 'GET_BOOKED_TRIP_SUCCESS'
export const GET_BOOKED_TRIP_FAIL = 'GET_BOOKED_TRIP_FAIL'

export const SAVE_PAYMENT_METHOD = 'SAVE_PAYMENT_METHOD'

export const TRIP_CREATE_REVIEW_REQUEST = 'TRIP_CREATE_REVIEW_REQUEST'
export const TRIP_CREATE_REVIEW_SUCCESS = 'TRIP_CREATE_REVIEW_SUCCESS'
export const TRIP_CREATE_REVIEW_FAIL = 'TRIP_CREATE_REVIEW_FAIL'
export const TRIP_CREATE_REVIEW_RESET = 'TRIP_CREATE_REVIEW_RESET'